language: python
# Test against 2.7
python:
  - "2.7"
cache:
  directories:
    - $HOME/.cache/pip
addons:
  postgresql: "9.4"
services:
  - postgresql
env:
  PIP_DOWNLOAD_CACHE=$HOME/.cache/pip
  DATABASE_URL=pgsql://postgres:@localhost:5432/everyvoter
  CACHE_URL=dummycache://
  SECRET_KEY=demo_secret_key
  GEOCODIO_KEY=DEMO
  CELERY_ALWAYS_EAGER=True
before_install:
   - pip install --upgrade pip
install:
  - pip install -r requirements.txt
# command to run tests
script:
# Fix for boto error on Travis
  - export BOTO_CONFIG=/dev/null
  - python manage.py test
# install and run pylint if everything passed
after_success:
  - pip install pylint==1.5.2
  - pylint --rcfile=.pylintrc accounts everyvoter_common election branding api user_import rendering geodataset hirefire staff
# turn off email notifications
notifications:
  email: false
